{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "ZUfPbTDXFvNq",
        "outputId": "7af8f94d-8ad0-4cee-e986-a79606c74bb4"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: fiftyone in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (1.3.2)\n",
            "Requirement already satisfied: aiofiles in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (24.1.0)\n",
            "Requirement already satisfied: argcomplete in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.6.0)\n",
            "Requirement already satisfied: beautifulsoup4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.13.3)\n",
            "Requirement already satisfied: boto3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.37.13)\n",
            "Requirement already satisfied: cachetools in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (5.5.2)\n",
            "Requirement already satisfied: dacite<1.8.0,>=1.6.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.7.0)\n",
            "Requirement already satisfied: Deprecated in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.2.18)\n",
            "Requirement already satisfied: ftfy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.3.1)\n",
            "Requirement already satisfied: humanize in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.12.1)\n",
            "Requirement already satisfied: hypercorn>=0.13.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.17.3)\n",
            "Requirement already satisfied: Jinja2>=3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.1.6)\n",
            "Requirement already satisfied: kaleido!=0.2.1.post1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.2.1)\n",
            "Requirement already satisfied: matplotlib in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.10.1)\n",
            "Requirement already satisfied: mongoengine~=0.29.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.29.1)\n",
            "Requirement already satisfied: motor~=3.6.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.6.1)\n",
            "Requirement already satisfied: numpy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2.2.3)\n",
            "Requirement already satisfied: packaging in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (24.2)\n",
            "Requirement already satisfied: pandas in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2.2.3)\n",
            "Requirement already satisfied: Pillow>=6.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (11.1.0)\n",
            "Requirement already satisfied: plotly>=4.14 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.0.0)\n",
            "Requirement already satisfied: pprintpp in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.4.0)\n",
            "Requirement already satisfied: psutil in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (5.9.0)\n",
            "Requirement already satisfied: pymongo~=4.9.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.9.2)\n",
            "Requirement already satisfied: pytz in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2025.1)\n",
            "Requirement already satisfied: PyYAML in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.0.2)\n",
            "Requirement already satisfied: regex in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2024.11.6)\n",
            "Requirement already satisfied: retrying in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.3.4)\n",
            "Requirement already satisfied: rtree in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.4.0)\n",
            "Requirement already satisfied: scikit-learn in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.6.1)\n",
            "Requirement already satisfied: scikit-image in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.25.2)\n",
            "Requirement already satisfied: scipy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.15.2)\n",
            "Requirement already satisfied: setuptools in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (75.8.0)\n",
            "Requirement already satisfied: sseclient-py<2,>=1.7.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.8.0)\n",
            "Requirement already satisfied: sse-starlette<1,>=0.10.3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.10.3)\n",
            "Requirement already satisfied: starlette>=0.24.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.46.1)\n",
            "Requirement already satisfied: strawberry-graphql in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.262.5)\n",
            "Requirement already satisfied: tabulate in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.9.0)\n",
            "Requirement already satisfied: xmltodict in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.14.2)\n",
            "Requirement already satisfied: universal-analytics-python3<2,>=1.0.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.1.1)\n",
            "Requirement already satisfied: pydash in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (8.0.5)\n",
            "Requirement already satisfied: fiftyone-brain<0.20,>=0.19.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.19.0)\n",
            "Requirement already satisfied: fiftyone-db<2.0,>=0.4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.1.7)\n",
            "Requirement already satisfied: voxel51-eta<0.15,>=0.14.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.14.0)\n",
            "Requirement already satisfied: opencv-python-headless in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.11.0.86)\n",
            "Requirement already satisfied: h11 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (0.14.0)\n",
            "Requirement already satisfied: h2>=3.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (4.2.0)\n",
            "Requirement already satisfied: priority in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (2.0.0)\n",
            "Requirement already satisfied: wsproto>=0.14.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (1.2.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from Jinja2>=3->fiftyone) (3.0.2)\n",
            "Requirement already satisfied: narwhals>=1.15.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from plotly>=4.14->fiftyone) (1.30.0)\n",
            "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from pymongo~=4.9.2->fiftyone) (2.7.0)\n",
            "Requirement already satisfied: anyio<5,>=3.6.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from starlette>=0.24.0->fiftyone) (4.8.0)\n",
            "Requirement already satisfied: httpx>=0.10.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from universal-analytics-python3<2,>=1.0.1->fiftyone) (0.28.1)\n",
            "Requirement already satisfied: dill in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.3.8)\n",
            "Requirement already satisfied: future in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.0)\n",
            "Requirement already satisfied: glob2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.7)\n",
            "Requirement already satisfied: jsonlines in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (4.0.0)\n",
            "Requirement already satisfied: py7zr in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.22.0)\n",
            "Requirement already satisfied: python-dateutil in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.9.0.post0)\n",
            "Requirement already satisfied: rarfile in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (4.2)\n",
            "Requirement already satisfied: requests in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.32.3)\n",
            "Requirement already satisfied: six in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (1.17.0)\n",
            "Requirement already satisfied: sortedcontainers in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.4.0)\n",
            "Requirement already satisfied: tzlocal in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (5.3.1)\n",
            "Requirement already satisfied: urllib3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.3.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from beautifulsoup4->fiftyone) (2.6)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from beautifulsoup4->fiftyone) (4.12.2)\n",
            "Requirement already satisfied: botocore<1.38.0,>=1.37.13 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (1.37.13)\n",
            "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (1.0.1)\n",
            "Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (0.11.4)\n",
            "Requirement already satisfied: wrapt<2,>=1.10 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from Deprecated->fiftyone) (1.17.2)\n",
            "Requirement already satisfied: wcwidth in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from ftfy->fiftyone) (0.2.13)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (1.3.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (4.56.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (1.4.8)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (3.2.1)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from pandas->fiftyone) (2025.1)\n",
            "Requirement already satisfied: networkx>=3.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (3.4.2)\n",
            "Requirement already satisfied: imageio!=2.35.0,>=2.33 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (2.37.0)\n",
            "Requirement already satisfied: tifffile>=2022.8.12 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (2025.3.13)\n",
            "Requirement already satisfied: lazy-loader>=0.4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (0.4)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-learn->fiftyone) (1.4.2)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-learn->fiftyone) (3.6.0)\n",
            "Requirement already satisfied: graphql-core<3.4.0,>=3.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from strawberry-graphql->fiftyone) (3.2.6)\n",
            "Requirement already satisfied: idna>=2.8 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from anyio<5,>=3.6.2->starlette>=0.24.0->fiftyone) (3.10)\n",
            "Requirement already satisfied: sniffio>=1.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from anyio<5,>=3.6.2->starlette>=0.24.0->fiftyone) (1.3.1)\n",
            "Requirement already satisfied: hyperframe<7,>=6.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from h2>=3.1.0->hypercorn>=0.13.2->fiftyone) (6.1.0)\n",
            "Requirement already satisfied: hpack<5,>=4.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from h2>=3.1.0->hypercorn>=0.13.2->fiftyone) (4.1.0)\n",
            "Requirement already satisfied: certifi in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from httpx>=0.10.0->universal-analytics-python3<2,>=1.0.1->fiftyone) (2025.1.31)\n",
            "Requirement already satisfied: httpcore==1.* in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from httpx>=0.10.0->universal-analytics-python3<2,>=1.0.1->fiftyone) (1.0.7)\n",
            "Requirement already satisfied: attrs>=19.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from jsonlines->voxel51-eta<0.15,>=0.14.0->fiftyone) (25.3.0)\n",
            "Requirement already satisfied: texttable in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.7.0)\n",
            "Requirement already satisfied: pycryptodomex>=3.16.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (3.21.0)\n",
            "Requirement already satisfied: pyzstd>=0.15.9 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (0.16.2)\n",
            "Requirement already satisfied: pyppmd<1.2.0,>=1.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.1.1)\n",
            "Requirement already satisfied: pybcj<1.1.0,>=1.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.3)\n",
            "Requirement already satisfied: multivolumefile>=0.2.3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (0.2.3)\n",
            "Requirement already satisfied: inflate64<1.1.0,>=1.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.1)\n",
            "Requirement already satisfied: brotli>=1.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.1.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from requests->voxel51-eta<0.15,>=0.14.0->fiftyone) (3.4.1)\n",
            "Note: you may need to restart the kernel to use updated packages.\n",
            "Requirement already satisfied: fiftyone in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (1.3.2)\n",
            "Collecting pyvips-binary\n",
            "  Downloading pyvips_binary-8.16.1-cp37-abi3-macosx_11_0_arm64.whl.metadata (2.3 kB)\n",
            "Collecting pyvips\n",
            "  Downloading pyvips-2.2.3.tar.gz (56 kB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25hRequirement already satisfied: aiofiles in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (24.1.0)\n",
            "Requirement already satisfied: argcomplete in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.6.0)\n",
            "Requirement already satisfied: beautifulsoup4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.13.3)\n",
            "Requirement already satisfied: boto3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.37.13)\n",
            "Requirement already satisfied: cachetools in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (5.5.2)\n",
            "Requirement already satisfied: dacite<1.8.0,>=1.6.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.7.0)\n",
            "Requirement already satisfied: Deprecated in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.2.18)\n",
            "Requirement already satisfied: ftfy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.3.1)\n",
            "Requirement already satisfied: humanize in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.12.1)\n",
            "Requirement already satisfied: hypercorn>=0.13.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.17.3)\n",
            "Requirement already satisfied: Jinja2>=3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.1.6)\n",
            "Requirement already satisfied: kaleido!=0.2.1.post1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.2.1)\n",
            "Requirement already satisfied: matplotlib in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.10.1)\n",
            "Requirement already satisfied: mongoengine~=0.29.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.29.1)\n",
            "Requirement already satisfied: motor~=3.6.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (3.6.1)\n",
            "Requirement already satisfied: numpy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2.2.3)\n",
            "Requirement already satisfied: packaging in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (24.2)\n",
            "Requirement already satisfied: pandas in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2.2.3)\n",
            "Requirement already satisfied: Pillow>=6.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (11.1.0)\n",
            "Requirement already satisfied: plotly>=4.14 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.0.0)\n",
            "Requirement already satisfied: pprintpp in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.4.0)\n",
            "Requirement already satisfied: psutil in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (5.9.0)\n",
            "Requirement already satisfied: pymongo~=4.9.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.9.2)\n",
            "Requirement already satisfied: pytz in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2025.1)\n",
            "Requirement already satisfied: PyYAML in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (6.0.2)\n",
            "Requirement already satisfied: regex in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (2024.11.6)\n",
            "Requirement already satisfied: retrying in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.3.4)\n",
            "Requirement already satisfied: rtree in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.4.0)\n",
            "Requirement already satisfied: scikit-learn in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.6.1)\n",
            "Requirement already satisfied: scikit-image in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.25.2)\n",
            "Requirement already satisfied: scipy in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.15.2)\n",
            "Requirement already satisfied: setuptools in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (75.8.0)\n",
            "Requirement already satisfied: sseclient-py<2,>=1.7.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.8.0)\n",
            "Requirement already satisfied: sse-starlette<1,>=0.10.3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.10.3)\n",
            "Requirement already satisfied: starlette>=0.24.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.46.1)\n",
            "Requirement already satisfied: strawberry-graphql in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.262.5)\n",
            "Requirement already satisfied: tabulate in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.9.0)\n",
            "Requirement already satisfied: xmltodict in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.14.2)\n",
            "Requirement already satisfied: universal-analytics-python3<2,>=1.0.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.1.1)\n",
            "Requirement already satisfied: pydash in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (8.0.5)\n",
            "Requirement already satisfied: fiftyone-brain<0.20,>=0.19.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.19.0)\n",
            "Requirement already satisfied: fiftyone-db<2.0,>=0.4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (1.1.7)\n",
            "Requirement already satisfied: voxel51-eta<0.15,>=0.14.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (0.14.0)\n",
            "Requirement already satisfied: opencv-python-headless in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from fiftyone) (4.11.0.86)\n",
            "Collecting cffi>=1.0.0 (from pyvips-binary)\n",
            "  Using cached cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (1.5 kB)\n",
            "Collecting pycparser (from cffi>=1.0.0->pyvips-binary)\n",
            "  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)\n",
            "Requirement already satisfied: h11 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (0.14.0)\n",
            "Requirement already satisfied: h2>=3.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (4.2.0)\n",
            "Requirement already satisfied: priority in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (2.0.0)\n",
            "Requirement already satisfied: wsproto>=0.14.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from hypercorn>=0.13.2->fiftyone) (1.2.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from Jinja2>=3->fiftyone) (3.0.2)\n",
            "Requirement already satisfied: narwhals>=1.15.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from plotly>=4.14->fiftyone) (1.30.0)\n",
            "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from pymongo~=4.9.2->fiftyone) (2.7.0)\n",
            "Requirement already satisfied: anyio<5,>=3.6.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from starlette>=0.24.0->fiftyone) (4.8.0)\n",
            "Requirement already satisfied: httpx>=0.10.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from universal-analytics-python3<2,>=1.0.1->fiftyone) (0.28.1)\n",
            "Requirement already satisfied: dill in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.3.8)\n",
            "Requirement already satisfied: future in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.0)\n",
            "Requirement already satisfied: glob2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.7)\n",
            "Requirement already satisfied: jsonlines in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (4.0.0)\n",
            "Requirement already satisfied: py7zr in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (0.22.0)\n",
            "Requirement already satisfied: python-dateutil in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.9.0.post0)\n",
            "Requirement already satisfied: rarfile in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (4.2)\n",
            "Requirement already satisfied: requests in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.32.3)\n",
            "Requirement already satisfied: six in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (1.17.0)\n",
            "Requirement already satisfied: sortedcontainers in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.4.0)\n",
            "Requirement already satisfied: tzlocal in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (5.3.1)\n",
            "Requirement already satisfied: urllib3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from voxel51-eta<0.15,>=0.14.0->fiftyone) (2.3.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from beautifulsoup4->fiftyone) (2.6)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from beautifulsoup4->fiftyone) (4.12.2)\n",
            "Requirement already satisfied: botocore<1.38.0,>=1.37.13 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (1.37.13)\n",
            "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (1.0.1)\n",
            "Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from boto3->fiftyone) (0.11.4)\n",
            "Requirement already satisfied: wrapt<2,>=1.10 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from Deprecated->fiftyone) (1.17.2)\n",
            "Requirement already satisfied: wcwidth in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from ftfy->fiftyone) (0.2.13)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (1.3.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (4.56.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (1.4.8)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from matplotlib->fiftyone) (3.2.1)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from pandas->fiftyone) (2025.1)\n",
            "Requirement already satisfied: networkx>=3.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (3.4.2)\n",
            "Requirement already satisfied: imageio!=2.35.0,>=2.33 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (2.37.0)\n",
            "Requirement already satisfied: tifffile>=2022.8.12 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (2025.3.13)\n",
            "Requirement already satisfied: lazy-loader>=0.4 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-image->fiftyone) (0.4)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-learn->fiftyone) (1.4.2)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from scikit-learn->fiftyone) (3.6.0)\n",
            "Requirement already satisfied: graphql-core<3.4.0,>=3.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from strawberry-graphql->fiftyone) (3.2.6)\n",
            "Requirement already satisfied: idna>=2.8 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from anyio<5,>=3.6.2->starlette>=0.24.0->fiftyone) (3.10)\n",
            "Requirement already satisfied: sniffio>=1.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from anyio<5,>=3.6.2->starlette>=0.24.0->fiftyone) (1.3.1)\n",
            "Requirement already satisfied: hyperframe<7,>=6.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from h2>=3.1.0->hypercorn>=0.13.2->fiftyone) (6.1.0)\n",
            "Requirement already satisfied: hpack<5,>=4.1 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from h2>=3.1.0->hypercorn>=0.13.2->fiftyone) (4.1.0)\n",
            "Requirement already satisfied: certifi in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from httpx>=0.10.0->universal-analytics-python3<2,>=1.0.1->fiftyone) (2025.1.31)\n",
            "Requirement already satisfied: httpcore==1.* in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from httpx>=0.10.0->universal-analytics-python3<2,>=1.0.1->fiftyone) (1.0.7)\n",
            "Requirement already satisfied: attrs>=19.2.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from jsonlines->voxel51-eta<0.15,>=0.14.0->fiftyone) (25.3.0)\n",
            "Requirement already satisfied: texttable in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.7.0)\n",
            "Requirement already satisfied: pycryptodomex>=3.16.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (3.21.0)\n",
            "Requirement already satisfied: pyzstd>=0.15.9 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (0.16.2)\n",
            "Requirement already satisfied: pyppmd<1.2.0,>=1.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.1.1)\n",
            "Requirement already satisfied: pybcj<1.1.0,>=1.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.3)\n",
            "Requirement already satisfied: multivolumefile>=0.2.3 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (0.2.3)\n",
            "Requirement already satisfied: inflate64<1.1.0,>=1.0.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.0.1)\n",
            "Requirement already satisfied: brotli>=1.1.0 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from py7zr->voxel51-eta<0.15,>=0.14.0->fiftyone) (1.1.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages (from requests->voxel51-eta<0.15,>=0.14.0->fiftyone) (3.4.1)\n",
            "Downloading pyvips_binary-8.16.1-cp37-abi3-macosx_11_0_arm64.whl (7.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.2/7.2 MB\u001b[0m \u001b[31m9.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mta \u001b[36m0:00:01\u001b[0m\n",
            "\u001b[?25hUsing cached cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl (178 kB)\n",
            "Using cached pycparser-2.22-py3-none-any.whl (117 kB)\n",
            "Building wheels for collected packages: pyvips\n",
            "  Building wheel for pyvips (setup.py) ... \u001b[?25lerror\n",
            "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
            "  \n",
            "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
            "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
            "  \u001b[31m╰─>\u001b[0m \u001b[31m[92 lines of output]\u001b[0m\n",
            "  \u001b[31m   \u001b[0m /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.\n",
            "  \u001b[31m   \u001b[0m !!\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
            "  \u001b[31m   \u001b[0m         Requirements should be satisfied by a PEP 517 installer.\n",
            "  \u001b[31m   \u001b[0m         If you are using pip, you can try `pip install --use-pep517`.\n",
            "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m !!\n",
            "  \u001b[31m   \u001b[0m   dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m Falling back to ABI mode. Details: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 123, in <module>\n",
            "  \u001b[31m   \u001b[0m     setup_API()\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 74, in setup_API\n",
            "  \u001b[31m   \u001b[0m     setup(\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 116, in setup\n",
            "  \u001b[31m   \u001b[0m     _install_setup_requires(attrs)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 89, in _install_setup_requires\n",
            "  \u001b[31m   \u001b[0m     _fetch_build_eggs(dist)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 94, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/dist.py\", line 663, in fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     return _fetch_build_eggs(self, requires)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 44, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
            "  \u001b[31m   \u001b[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 888, in resolve\n",
            "  \u001b[31m   \u001b[0m     dist = self._resolve_dist(\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 924, in _resolve_dist\n",
            "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
            "  \u001b[31m   \u001b[0m                            ^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1262, in best_match\n",
            "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1298, in obtain\n",
            "  \u001b[31m   \u001b[0m     return installer(requirement) if installer else None\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 112, in _fetch_build_egg_no_warn\n",
            "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 122, in install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 130, in _install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 175, in _convert_metadata\n",
            "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
            "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
            "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 126, in <module>\n",
            "  \u001b[31m   \u001b[0m     setup_ABI()\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 98, in setup_ABI\n",
            "  \u001b[31m   \u001b[0m     setup(\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 116, in setup\n",
            "  \u001b[31m   \u001b[0m     _install_setup_requires(attrs)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 89, in _install_setup_requires\n",
            "  \u001b[31m   \u001b[0m     _fetch_build_eggs(dist)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 94, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/dist.py\", line 663, in fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     return _fetch_build_eggs(self, requires)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 44, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
            "  \u001b[31m   \u001b[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 888, in resolve\n",
            "  \u001b[31m   \u001b[0m     dist = self._resolve_dist(\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 924, in _resolve_dist\n",
            "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
            "  \u001b[31m   \u001b[0m                            ^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1262, in best_match\n",
            "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1298, in obtain\n",
            "  \u001b[31m   \u001b[0m     return installer(requirement) if installer else None\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 112, in _fetch_build_egg_no_warn\n",
            "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 122, in install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 130, in _install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 175, in _convert_metadata\n",
            "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
            "  \n",
            "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "\u001b[31m  ERROR: Failed building wheel for pyvips\u001b[0m\u001b[31m\n",
            "\u001b[0m\u001b[?25h  Running setup.py clean for pyvips\n",
            "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
            "  \n",
            "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py clean\u001b[0m did not run successfully.\n",
            "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
            "  \u001b[31m╰─>\u001b[0m \u001b[31m[92 lines of output]\u001b[0m\n",
            "  \u001b[31m   \u001b[0m /opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.\n",
            "  \u001b[31m   \u001b[0m !!\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
            "  \u001b[31m   \u001b[0m         Requirements should be satisfied by a PEP 517 installer.\n",
            "  \u001b[31m   \u001b[0m         If you are using pip, you can try `pip install --use-pep517`.\n",
            "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m !!\n",
            "  \u001b[31m   \u001b[0m   dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m Falling back to ABI mode. Details: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 123, in <module>\n",
            "  \u001b[31m   \u001b[0m     setup_API()\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 74, in setup_API\n",
            "  \u001b[31m   \u001b[0m     setup(\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 116, in setup\n",
            "  \u001b[31m   \u001b[0m     _install_setup_requires(attrs)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 89, in _install_setup_requires\n",
            "  \u001b[31m   \u001b[0m     _fetch_build_eggs(dist)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 94, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/dist.py\", line 663, in fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     return _fetch_build_eggs(self, requires)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 44, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
            "  \u001b[31m   \u001b[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 888, in resolve\n",
            "  \u001b[31m   \u001b[0m     dist = self._resolve_dist(\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 924, in _resolve_dist\n",
            "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
            "  \u001b[31m   \u001b[0m                            ^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1262, in best_match\n",
            "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1298, in obtain\n",
            "  \u001b[31m   \u001b[0m     return installer(requirement) if installer else None\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 112, in _fetch_build_egg_no_warn\n",
            "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 122, in install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 130, in _install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 175, in _convert_metadata\n",
            "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
            "  \u001b[31m   \u001b[0m \n",
            "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
            "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
            "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 126, in <module>\n",
            "  \u001b[31m   \u001b[0m     setup_ABI()\n",
            "  \u001b[31m   \u001b[0m   File \"/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/setup.py\", line 98, in setup_ABI\n",
            "  \u001b[31m   \u001b[0m     setup(\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 116, in setup\n",
            "  \u001b[31m   \u001b[0m     _install_setup_requires(attrs)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 89, in _install_setup_requires\n",
            "  \u001b[31m   \u001b[0m     _fetch_build_eggs(dist)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/__init__.py\", line 94, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     dist.fetch_build_eggs(dist.setup_requires)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/dist.py\", line 663, in fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     return _fetch_build_eggs(self, requires)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 44, in _fetch_build_eggs\n",
            "  \u001b[31m   \u001b[0m     resolved_dists = pkg_resources.working_set.resolve(\n",
            "  \u001b[31m   \u001b[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 888, in resolve\n",
            "  \u001b[31m   \u001b[0m     dist = self._resolve_dist(\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 924, in _resolve_dist\n",
            "  \u001b[31m   \u001b[0m     dist = best[req.key] = env.best_match(\n",
            "  \u001b[31m   \u001b[0m                            ^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1262, in best_match\n",
            "  \u001b[31m   \u001b[0m     return self.obtain(req, installer)\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/pkg_resources/__init__.py\", line 1298, in obtain\n",
            "  \u001b[31m   \u001b[0m     return installer(requirement) if installer else None\n",
            "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/installer.py\", line 112, in _fetch_build_egg_no_warn\n",
            "  \u001b[31m   \u001b[0m     wheel.install_as_egg(dist_location)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 122, in install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._install_as_egg(destination_eggdir, zf)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 130, in _install_as_egg\n",
            "  \u001b[31m   \u001b[0m     self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/setuptools/wheel.py\", line 175, in _convert_metadata\n",
            "  \u001b[31m   \u001b[0m     os.rename(dist_info, egg_info)\n",
            "  \u001b[31m   \u001b[0m OSError: [Errno 66] Directory not empty: '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/cffi-1.17.1.dist-info' -> '/private/var/folders/n1/46p_whwd2lj1f5lzxn7p0xnm0000gn/T/pip-install-1fv7q24p/pyvips_b16a1434609d41b188cd79681663d6ef/.eggs/cffi-1.17.1-py3.11-macosx-11.1-arm64.egg/EGG-INFO'\n",
            "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
            "  \n",
            "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "\u001b[31m  ERROR: Failed cleaning build dir for pyvips\u001b[0m\u001b[31m\n",
            "\u001b[0mFailed to build pyvips\n",
            "\u001b[31mERROR: Failed to build installable wheels for some pyproject.toml based projects (pyvips)\u001b[0m\u001b[31m\n",
            "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
            "Downloading harpreetsahota204/moondream2-plugin...\n",
            "  118.4Kb [66.2ms elapsed, ? remaining, 1.7Mb/s] \n",
            "Copying plugin '@harpreetsahota/moondream2' to '/Users/mingz/fiftyone/__plugins__/@harpreetsahota/moondream2'\n"
          ]
        },
        {
          "data": {
            "text/plain": [
              "{'@harpreetsahota/moondream2': '/Users/mingz/fiftyone/__plugins__/@harpreetsahota/moondream2'}"
            ]
          },
          "execution_count": 2,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "%pip install -U fiftyone\n",
        "%pip install fiftyone pyvips-binary pyvips\n",
        "\n",
        "import fiftyone.plugins as fop\n",
        "fop.download_plugin(\"https://github.com/harpreetsahota204/moondream2-plugin\")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "X-Hd3YSuGGOa",
        "outputId": "0ddcaf9e-7578-431a-b1b5-fe1176caf1be"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
            "  from .autonotebook import tqdm as notebook_tqdm\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Downloading config file fiftyone.yml from Chirag-R/foods\n",
            "Loading dataset\n",
            "Importing samples...\n",
            " 100% |███████████████| 3986/3986 [33.7ms elapsed, 0s remaining, 118.4K samples/s]  \n",
            "Downloading 3986 media files...\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            " 50%|█████     | 20/40 [02:03<02:03,  6.17s/it]\n"
          ]
        },
        {
          "ename": "LocalEntryNotFoundError",
          "evalue": "An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.",
          "output_type": "error",
          "traceback": [
            "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
            "\u001b[31mTimeoutError\u001b[39m                              Traceback (most recent call last)",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connectionpool.py:534\u001b[39m, in \u001b[36mHTTPConnectionPool._make_request\u001b[39m\u001b[34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[39m\n\u001b[32m    533\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m534\u001b[39m     response = \u001b[43mconn\u001b[49m\u001b[43m.\u001b[49m\u001b[43mgetresponse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    535\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (BaseSSLError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connection.py:516\u001b[39m, in \u001b[36mHTTPConnection.getresponse\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    515\u001b[39m \u001b[38;5;66;03m# Get the response from http.client.HTTPConnection\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m516\u001b[39m httplib_response = \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43mgetresponse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    518\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/http/client.py:1395\u001b[39m, in \u001b[36mHTTPConnection.getresponse\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   1394\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1395\u001b[39m     \u001b[43mresponse\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbegin\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1396\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/http/client.py:325\u001b[39m, in \u001b[36mHTTPResponse.begin\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    324\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m325\u001b[39m     version, status, reason = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_read_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    326\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m status != CONTINUE:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/http/client.py:286\u001b[39m, in \u001b[36mHTTPResponse._read_status\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    285\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_read_status\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[32m--> \u001b[39m\u001b[32m286\u001b[39m     line = \u001b[38;5;28mstr\u001b[39m(\u001b[38;5;28mself\u001b[39m.fp.readline(_MAXLINE + \u001b[32m1\u001b[39m), \u001b[33m\"\u001b[39m\u001b[33miso-8859-1\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    287\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(line) > _MAXLINE:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/socket.py:718\u001b[39m, in \u001b[36mSocketIO.readinto\u001b[39m\u001b[34m(self, b)\u001b[39m\n\u001b[32m    717\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m718\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_sock\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrecv_into\u001b[49m\u001b[43m(\u001b[49m\u001b[43mb\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    719\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m timeout:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/ssl.py:1314\u001b[39m, in \u001b[36mSSLSocket.recv_into\u001b[39m\u001b[34m(self, buffer, nbytes, flags)\u001b[39m\n\u001b[32m   1311\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m   1312\u001b[39m           \u001b[33m\"\u001b[39m\u001b[33mnon-zero flags not allowed in calls to recv_into() on \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m %\n\u001b[32m   1313\u001b[39m           \u001b[38;5;28mself\u001b[39m.\u001b[34m__class__\u001b[39m)\n\u001b[32m-> \u001b[39m\u001b[32m1314\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mread\u001b[49m\u001b[43m(\u001b[49m\u001b[43mnbytes\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbuffer\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1315\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/ssl.py:1166\u001b[39m, in \u001b[36mSSLSocket.read\u001b[39m\u001b[34m(self, len, buffer)\u001b[39m\n\u001b[32m   1165\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m buffer \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1166\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_sslobj\u001b[49m\u001b[43m.\u001b[49m\u001b[43mread\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbuffer\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1167\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n",
            "\u001b[31mTimeoutError\u001b[39m: The read operation timed out",
            "\nThe above exception was the direct cause of the following exception:\n",
            "\u001b[31mReadTimeoutError\u001b[39m                          Traceback (most recent call last)",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/requests/adapters.py:667\u001b[39m, in \u001b[36mHTTPAdapter.send\u001b[39m\u001b[34m(self, request, stream, timeout, verify, cert, proxies)\u001b[39m\n\u001b[32m    666\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m667\u001b[39m     resp = \u001b[43mconn\u001b[49m\u001b[43m.\u001b[49m\u001b[43murlopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    668\u001b[39m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m.\u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    669\u001b[39m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    670\u001b[39m \u001b[43m        \u001b[49m\u001b[43mbody\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    671\u001b[39m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m.\u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    672\u001b[39m \u001b[43m        \u001b[49m\u001b[43mredirect\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    673\u001b[39m \u001b[43m        \u001b[49m\u001b[43massert_same_host\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    674\u001b[39m \u001b[43m        \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    675\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    676\u001b[39m \u001b[43m        \u001b[49m\u001b[43mretries\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    677\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    678\u001b[39m \u001b[43m        \u001b[49m\u001b[43mchunked\u001b[49m\u001b[43m=\u001b[49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    679\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    681\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (ProtocolError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connectionpool.py:841\u001b[39m, in \u001b[36mHTTPConnectionPool.urlopen\u001b[39m\u001b[34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[39m\n\u001b[32m    839\u001b[39m     new_e = ProtocolError(\u001b[33m\"\u001b[39m\u001b[33mConnection aborted.\u001b[39m\u001b[33m\"\u001b[39m, new_e)\n\u001b[32m--> \u001b[39m\u001b[32m841\u001b[39m retries = \u001b[43mretries\u001b[49m\u001b[43m.\u001b[49m\u001b[43mincrement\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    842\u001b[39m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror\u001b[49m\u001b[43m=\u001b[49m\u001b[43mnew_e\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_pool\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_stacktrace\u001b[49m\u001b[43m=\u001b[49m\u001b[43msys\u001b[49m\u001b[43m.\u001b[49m\u001b[43mexc_info\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[32;43m2\u001b[39;49m\u001b[43m]\u001b[49m\n\u001b[32m    843\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    844\u001b[39m retries.sleep()\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/util/retry.py:474\u001b[39m, in \u001b[36mRetry.increment\u001b[39m\u001b[34m(self, method, url, response, error, _pool, _stacktrace)\u001b[39m\n\u001b[32m    473\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m read \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m \u001b[38;5;129;01mor\u001b[39;00m method \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m._is_method_retryable(method):\n\u001b[32m--> \u001b[39m\u001b[32m474\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[43mreraise\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mtype\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43merror\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_stacktrace\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    475\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m read \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/util/util.py:39\u001b[39m, in \u001b[36mreraise\u001b[39m\u001b[34m(tp, value, tb)\u001b[39m\n\u001b[32m     38\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m value.with_traceback(tb)\n\u001b[32m---> \u001b[39m\u001b[32m39\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m value\n\u001b[32m     40\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connectionpool.py:787\u001b[39m, in \u001b[36mHTTPConnectionPool.urlopen\u001b[39m\u001b[34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[39m\n\u001b[32m    786\u001b[39m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m787\u001b[39m response = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_make_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    788\u001b[39m \u001b[43m    \u001b[49m\u001b[43mconn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    789\u001b[39m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    790\u001b[39m \u001b[43m    \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    791\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtimeout_obj\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    792\u001b[39m \u001b[43m    \u001b[49m\u001b[43mbody\u001b[49m\u001b[43m=\u001b[49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    793\u001b[39m \u001b[43m    \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    794\u001b[39m \u001b[43m    \u001b[49m\u001b[43mchunked\u001b[49m\u001b[43m=\u001b[49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    795\u001b[39m \u001b[43m    \u001b[49m\u001b[43mretries\u001b[49m\u001b[43m=\u001b[49m\u001b[43mretries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    796\u001b[39m \u001b[43m    \u001b[49m\u001b[43mresponse_conn\u001b[49m\u001b[43m=\u001b[49m\u001b[43mresponse_conn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    797\u001b[39m \u001b[43m    \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[43m=\u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    798\u001b[39m \u001b[43m    \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[43m=\u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    799\u001b[39m \u001b[43m    \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mresponse_kw\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    800\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    802\u001b[39m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connectionpool.py:536\u001b[39m, in \u001b[36mHTTPConnectionPool._make_request\u001b[39m\u001b[34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[39m\n\u001b[32m    535\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (BaseSSLError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m--> \u001b[39m\u001b[32m536\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_raise_timeout\u001b[49m\u001b[43m(\u001b[49m\u001b[43merr\u001b[49m\u001b[43m=\u001b[49m\u001b[43me\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout_value\u001b[49m\u001b[43m=\u001b[49m\u001b[43mread_timeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    537\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/urllib3/connectionpool.py:367\u001b[39m, in \u001b[36mHTTPConnectionPool._raise_timeout\u001b[39m\u001b[34m(self, err, url, timeout_value)\u001b[39m\n\u001b[32m    366\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(err, SocketTimeout):\n\u001b[32m--> \u001b[39m\u001b[32m367\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m ReadTimeoutError(\n\u001b[32m    368\u001b[39m         \u001b[38;5;28mself\u001b[39m, url, \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mRead timed out. (read timeout=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mtimeout_value\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m)\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    369\u001b[39m     ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    371\u001b[39m \u001b[38;5;66;03m# See the above comment about EAGAIN in Python 3.\u001b[39;00m\n",
            "\u001b[31mReadTimeoutError\u001b[39m: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)",
            "\nDuring handling of the above exception, another exception occurred:\n",
            "\u001b[31mReadTimeout\u001b[39m                               Traceback (most recent call last)",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:1376\u001b[39m, in \u001b[36m_get_metadata_or_catch_error\u001b[39m\u001b[34m(repo_id, filename, repo_type, revision, endpoint, proxies, etag_timeout, headers, token, local_files_only, relative_filename, storage_folder)\u001b[39m\n\u001b[32m   1375\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1376\u001b[39m     metadata = \u001b[43mget_hf_file_metadata\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m   1377\u001b[39m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m=\u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43metag_timeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtoken\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtoken\u001b[49m\n\u001b[32m   1378\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1379\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m EntryNotFoundError \u001b[38;5;28;01mas\u001b[39;00m http_error:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py:114\u001b[39m, in \u001b[36mvalidate_hf_hub_args.<locals>._inner_fn\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    112\u001b[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001b[34m__name__\u001b[39m, has_token=has_token, kwargs=kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m114\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:1296\u001b[39m, in \u001b[36mget_hf_file_metadata\u001b[39m\u001b[34m(url, token, proxies, timeout, library_name, library_version, user_agent, headers)\u001b[39m\n\u001b[32m   1295\u001b[39m \u001b[38;5;66;03m# Retrieve metadata\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m1296\u001b[39m r = \u001b[43m_request_wrapper\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m   1297\u001b[39m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mHEAD\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m   1298\u001b[39m \u001b[43m    \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1299\u001b[39m \u001b[43m    \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mhf_headers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1300\u001b[39m \u001b[43m    \u001b[49m\u001b[43mallow_redirects\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m   1301\u001b[39m \u001b[43m    \u001b[49m\u001b[43mfollow_relative_redirects\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m   1302\u001b[39m \u001b[43m    \u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m=\u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1303\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1304\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1305\u001b[39m hf_raise_for_status(r)\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:280\u001b[39m, in \u001b[36m_request_wrapper\u001b[39m\u001b[34m(method, url, follow_relative_redirects, **params)\u001b[39m\n\u001b[32m    279\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m follow_relative_redirects:\n\u001b[32m--> \u001b[39m\u001b[32m280\u001b[39m     response = \u001b[43m_request_wrapper\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    281\u001b[39m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    282\u001b[39m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    283\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfollow_relative_redirects\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    284\u001b[39m \u001b[43m        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mparams\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    285\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    287\u001b[39m     \u001b[38;5;66;03m# If redirection, we redirect only relative paths.\u001b[39;00m\n\u001b[32m    288\u001b[39m     \u001b[38;5;66;03m# This is useful in case of a renamed repository.\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:303\u001b[39m, in \u001b[36m_request_wrapper\u001b[39m\u001b[34m(method, url, follow_relative_redirects, **params)\u001b[39m\n\u001b[32m    302\u001b[39m \u001b[38;5;66;03m# Perform request and return if status_code is not in the retry list.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m303\u001b[39m response = \u001b[43mget_session\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m=\u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mparams\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    304\u001b[39m hf_raise_for_status(response)\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/requests/sessions.py:589\u001b[39m, in \u001b[36mSession.request\u001b[39m\u001b[34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[39m\n\u001b[32m    588\u001b[39m send_kwargs.update(settings)\n\u001b[32m--> \u001b[39m\u001b[32m589\u001b[39m resp = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprep\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43msend_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    591\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/requests/sessions.py:703\u001b[39m, in \u001b[36mSession.send\u001b[39m\u001b[34m(self, request, **kwargs)\u001b[39m\n\u001b[32m    702\u001b[39m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m703\u001b[39m r = \u001b[43madapter\u001b[49m\u001b[43m.\u001b[49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    705\u001b[39m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/utils/_http.py:96\u001b[39m, in \u001b[36mUniqueRequestIdAdapter.send\u001b[39m\u001b[34m(self, request, *args, **kwargs)\u001b[39m\n\u001b[32m     95\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m96\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     97\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m requests.RequestException \u001b[38;5;28;01mas\u001b[39;00m e:\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/requests/adapters.py:713\u001b[39m, in \u001b[36mHTTPAdapter.send\u001b[39m\u001b[34m(self, request, stream, timeout, verify, cert, proxies)\u001b[39m\n\u001b[32m    712\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(e, ReadTimeoutError):\n\u001b[32m--> \u001b[39m\u001b[32m713\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m ReadTimeout(e, request=request)\n\u001b[32m    714\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(e, _InvalidHeader):\n",
            "\u001b[31mReadTimeout\u001b[39m: (ReadTimeoutError(\"HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)\"), '(Request ID: 7df305a0-cb8b-439b-890d-0fb1e6513fe3)')",
            "\nThe above exception was the direct cause of the following exception:\n",
            "\u001b[31mLocalEntryNotFoundError\u001b[39m                   Traceback (most recent call last)",
            "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 6\u001b[39m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mfiftyone\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mutils\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mhuggingface\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m load_from_hub\n\u001b[32m      4\u001b[39m \u001b[38;5;66;03m# Load the dataset\u001b[39;00m\n\u001b[32m      5\u001b[39m \u001b[38;5;66;03m# Note: other available arguments include 'max_samples', etc\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m6\u001b[39m dataset = \u001b[43mload_from_hub\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mChirag-R/foods\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moverwrite\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[32m      8\u001b[39m \u001b[38;5;66;03m# Launch the App\u001b[39;00m\n\u001b[32m      9\u001b[39m session = fo.launch_app(dataset)\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/fiftyone/utils/huggingface.py:323\u001b[39m, in \u001b[36mload_from_hub\u001b[39m\u001b[34m(repo_id, revision, split, splits, subset, subsets, max_samples, batch_size, num_workers, overwrite, persistent, name, token, config_file, **kwargs)\u001b[39m\n\u001b[32m    320\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m config \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    321\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mCould not find fiftyone metadata for \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mrepo_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m323\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_load_dataset_from_config\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/fiftyone/utils/huggingface.py:899\u001b[39m, in \u001b[36m_load_dataset_from_config\u001b[39m\u001b[34m(config, **kwargs)\u001b[39m\n\u001b[32m    897\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m _load_parquet_files_dataset_from_config(config, **kwargs)\n\u001b[32m    898\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m899\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_load_fiftyone_dataset_from_config\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/fiftyone/utils/huggingface.py:1508\u001b[39m, in \u001b[36m_load_fiftyone_dataset_from_config\u001b[39m\u001b[34m(config, **kwargs)\u001b[39m\n\u001b[32m   1505\u001b[39m filepaths = _get_files_to_download(dataset)\n\u001b[32m   1507\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m filepaths:\n\u001b[32m-> \u001b[39m\u001b[32m1508\u001b[39m     \u001b[43m_download_files_in_batches\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m   1509\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfilepaths\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdownload_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43minit_download_kwargs\u001b[49m\n\u001b[32m   1510\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1512\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m app_media_fields != [\u001b[33m\"\u001b[39m\u001b[33mfilepath\u001b[39m\u001b[33m\"\u001b[39m]:\n\u001b[32m   1513\u001b[39m     dataset.app_config.media_fields = app_media_fields\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/fiftyone/utils/huggingface.py:1534\u001b[39m, in \u001b[36m_download_files_in_batches\u001b[39m\u001b[34m(filepaths, download_dir, batch_size, **init_download_kwargs)\u001b[39m\n\u001b[32m   1532\u001b[39m batch_paths = rel_paths[start_idx:end_idx]\n\u001b[32m   1533\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m _no_progress_bars():\n\u001b[32m-> \u001b[39m\u001b[32m1534\u001b[39m     \u001b[43mhfh\u001b[49m\u001b[43m.\u001b[49m\u001b[43msnapshot_download\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m   1535\u001b[39m \u001b[43m        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43minit_download_kwargs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mallow_patterns\u001b[49m\u001b[43m=\u001b[49m\u001b[43mbatch_paths\u001b[49m\n\u001b[32m   1536\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py:114\u001b[39m, in \u001b[36mvalidate_hf_hub_args.<locals>._inner_fn\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    111\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m check_use_auth_token:\n\u001b[32m    112\u001b[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001b[34m__name__\u001b[39m, has_token=has_token, kwargs=kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m114\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py:296\u001b[39m, in \u001b[36msnapshot_download\u001b[39m\u001b[34m(repo_id, repo_type, revision, cache_dir, local_dir, library_name, library_version, user_agent, proxies, etag_timeout, force_download, token, local_files_only, allow_patterns, ignore_patterns, max_workers, tqdm_class, headers, endpoint, local_dir_use_symlinks, resume_download)\u001b[39m\n\u001b[32m    294\u001b[39m         _inner_hf_hub_download(file)\n\u001b[32m    295\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m296\u001b[39m     \u001b[43mthread_map\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    297\u001b[39m \u001b[43m        \u001b[49m\u001b[43m_inner_hf_hub_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    298\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfiltered_repo_files\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    299\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdesc\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43mf\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mFetching \u001b[39;49m\u001b[38;5;132;43;01m{\u001b[39;49;00m\u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mfiltered_repo_files\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;132;43;01m}\u001b[39;49;00m\u001b[33;43m files\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    300\u001b[39m \u001b[43m        \u001b[49m\u001b[43mmax_workers\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmax_workers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    301\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;66;43;03m# User can use its own tqdm class or the default one from `huggingface_hub.utils`\u001b[39;49;00m\n\u001b[32m    302\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtqdm_class\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtqdm_class\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mhf_tqdm\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    303\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    305\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m local_dir \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    306\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mstr\u001b[39m(os.path.realpath(local_dir))\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/tqdm/contrib/concurrent.py:69\u001b[39m, in \u001b[36mthread_map\u001b[39m\u001b[34m(fn, *iterables, **tqdm_kwargs)\u001b[39m\n\u001b[32m     55\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m     56\u001b[39m \u001b[33;03mEquivalent of `list(map(fn, *iterables))`\u001b[39;00m\n\u001b[32m     57\u001b[39m \u001b[33;03mdriven by `concurrent.futures.ThreadPoolExecutor`.\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m     66\u001b[39m \u001b[33;03m    [default: max(32, cpu_count() + 4)].\u001b[39;00m\n\u001b[32m     67\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m     68\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mconcurrent\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mfutures\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m ThreadPoolExecutor\n\u001b[32m---> \u001b[39m\u001b[32m69\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_executor_map\u001b[49m\u001b[43m(\u001b[49m\u001b[43mThreadPoolExecutor\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfn\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43miterables\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mtqdm_kwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/tqdm/contrib/concurrent.py:51\u001b[39m, in \u001b[36m_executor_map\u001b[39m\u001b[34m(PoolExecutor, fn, *iterables, **tqdm_kwargs)\u001b[39m\n\u001b[32m     47\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m ensure_lock(tqdm_class, lock_name=lock_name) \u001b[38;5;28;01mas\u001b[39;00m lk:\n\u001b[32m     48\u001b[39m     \u001b[38;5;66;03m# share lock in case workers are already using `tqdm`\u001b[39;00m\n\u001b[32m     49\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m PoolExecutor(max_workers=max_workers, initializer=tqdm_class.set_lock,\n\u001b[32m     50\u001b[39m                       initargs=(lk,)) \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[32m---> \u001b[39m\u001b[32m51\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mlist\u001b[39m(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/tqdm/std.py:1169\u001b[39m, in \u001b[36mtqdm.__iter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   1166\u001b[39m \u001b[38;5;66;03m# If the bar is disabled, then just walk the iterable\u001b[39;00m\n\u001b[32m   1167\u001b[39m \u001b[38;5;66;03m# (note: keep this check outside the loop for performance)\u001b[39;00m\n\u001b[32m   1168\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m.disable:\n\u001b[32m-> \u001b[39m\u001b[32m1169\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mobj\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43miterable\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m   1170\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;28;43;01myield\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mobj\u001b[49m\n\u001b[32m   1171\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/concurrent/futures/_base.py:619\u001b[39m, in \u001b[36mExecutor.map.<locals>.result_iterator\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m    616\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m fs:\n\u001b[32m    617\u001b[39m     \u001b[38;5;66;03m# Careful not to keep a reference to the popped future\u001b[39;00m\n\u001b[32m    618\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m619\u001b[39m         \u001b[38;5;28;01myield\u001b[39;00m \u001b[43m_result_or_cancel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mpop\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    620\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    621\u001b[39m         \u001b[38;5;28;01myield\u001b[39;00m _result_or_cancel(fs.pop(), end_time - time.monotonic())\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/concurrent/futures/_base.py:317\u001b[39m, in \u001b[36m_result_or_cancel\u001b[39m\u001b[34m(***failed resolving arguments***)\u001b[39m\n\u001b[32m    315\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    316\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m317\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfut\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    318\u001b[39m     \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    319\u001b[39m         fut.cancel()\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/concurrent/futures/_base.py:456\u001b[39m, in \u001b[36mFuture.result\u001b[39m\u001b[34m(self, timeout)\u001b[39m\n\u001b[32m    454\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m CancelledError()\n\u001b[32m    455\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._state == FINISHED:\n\u001b[32m--> \u001b[39m\u001b[32m456\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m__get_result\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    457\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    458\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTimeoutError\u001b[39;00m()\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/concurrent/futures/_base.py:401\u001b[39m, in \u001b[36mFuture.__get_result\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    399\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._exception:\n\u001b[32m    400\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m401\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m._exception\n\u001b[32m    402\u001b[39m     \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    403\u001b[39m         \u001b[38;5;66;03m# Break a reference cycle with the exception in self._exception\u001b[39;00m\n\u001b[32m    404\u001b[39m         \u001b[38;5;28mself\u001b[39m = \u001b[38;5;28;01mNone\u001b[39;00m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/concurrent/futures/thread.py:58\u001b[39m, in \u001b[36m_WorkItem.run\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m     55\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m\n\u001b[32m     57\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m58\u001b[39m     result = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     59\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m     60\u001b[39m     \u001b[38;5;28mself\u001b[39m.future.set_exception(exc)\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py:270\u001b[39m, in \u001b[36msnapshot_download.<locals>._inner_hf_hub_download\u001b[39m\u001b[34m(repo_file)\u001b[39m\n\u001b[32m    269\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_inner_hf_hub_download\u001b[39m(repo_file: \u001b[38;5;28mstr\u001b[39m):\n\u001b[32m--> \u001b[39m\u001b[32m270\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mhf_hub_download\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    271\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrepo_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    272\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrepo_file\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    273\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrepo_type\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrepo_type\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    274\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrevision\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcommit_hash\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    275\u001b[39m \u001b[43m        \u001b[49m\u001b[43mendpoint\u001b[49m\u001b[43m=\u001b[49m\u001b[43mendpoint\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    276\u001b[39m \u001b[43m        \u001b[49m\u001b[43mcache_dir\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcache_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    277\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    278\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlocal_dir_use_symlinks\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlocal_dir_use_symlinks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    279\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlibrary_name\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlibrary_name\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    280\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlibrary_version\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlibrary_version\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    281\u001b[39m \u001b[43m        \u001b[49m\u001b[43muser_agent\u001b[49m\u001b[43m=\u001b[49m\u001b[43muser_agent\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    282\u001b[39m \u001b[43m        \u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m=\u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    283\u001b[39m \u001b[43m        \u001b[49m\u001b[43metag_timeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43metag_timeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    284\u001b[39m \u001b[43m        \u001b[49m\u001b[43mresume_download\u001b[49m\u001b[43m=\u001b[49m\u001b[43mresume_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    285\u001b[39m \u001b[43m        \u001b[49m\u001b[43mforce_download\u001b[49m\u001b[43m=\u001b[49m\u001b[43mforce_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    286\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtoken\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtoken\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    287\u001b[39m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    288\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py:114\u001b[39m, in \u001b[36mvalidate_hf_hub_args.<locals>._inner_fn\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    111\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m check_use_auth_token:\n\u001b[32m    112\u001b[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001b[34m__name__\u001b[39m, has_token=has_token, kwargs=kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m114\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:842\u001b[39m, in \u001b[36mhf_hub_download\u001b[39m\u001b[34m(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, local_dir, user_agent, force_download, proxies, etag_timeout, token, local_files_only, headers, endpoint, resume_download, force_filename, local_dir_use_symlinks)\u001b[39m\n\u001b[32m    833\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m local_dir_use_symlinks != \u001b[33m\"\u001b[39m\u001b[33mauto\u001b[39m\u001b[33m\"\u001b[39m:\n\u001b[32m    834\u001b[39m         warnings.warn(\n\u001b[32m    835\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33m`local_dir_use_symlinks` parameter is deprecated and will be ignored. \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    836\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33mThe process to download files to a local folder has been updated and do \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m   (...)\u001b[39m\u001b[32m    839\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33mFor more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    840\u001b[39m         )\n\u001b[32m--> \u001b[39m\u001b[32m842\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_hf_hub_download_to_local_dir\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    843\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;66;43;03m# Destination\u001b[39;49;00m\n\u001b[32m    844\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    845\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;66;43;03m# File info\u001b[39;49;00m\n\u001b[32m    846\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrepo_id\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrepo_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    847\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrepo_type\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrepo_type\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    848\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m=\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    849\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrevision\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrevision\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    850\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;66;43;03m# HTTP info\u001b[39;49;00m\n\u001b[32m    851\u001b[39m \u001b[43m        \u001b[49m\u001b[43mendpoint\u001b[49m\u001b[43m=\u001b[49m\u001b[43mendpoint\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    852\u001b[39m \u001b[43m        \u001b[49m\u001b[43metag_timeout\u001b[49m\u001b[43m=\u001b[49m\u001b[43metag_timeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    853\u001b[39m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[43m=\u001b[49m\u001b[43mhf_headers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    854\u001b[39m \u001b[43m        \u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m=\u001b[49m\u001b[43mproxies\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    855\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtoken\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtoken\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    856\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;66;43;03m# Additional options\u001b[39;49;00m\n\u001b[32m    857\u001b[39m \u001b[43m        \u001b[49m\u001b[43mcache_dir\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcache_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    858\u001b[39m \u001b[43m        \u001b[49m\u001b[43mforce_download\u001b[49m\u001b[43m=\u001b[49m\u001b[43mforce_download\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    859\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlocal_files_only\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlocal_files_only\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    860\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    861\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    862\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m _hf_hub_download_to_cache_dir(\n\u001b[32m    863\u001b[39m         \u001b[38;5;66;03m# Destination\u001b[39;00m\n\u001b[32m    864\u001b[39m         cache_dir=cache_dir,\n\u001b[32m   (...)\u001b[39m\u001b[32m    878\u001b[39m         force_download=force_download,\n\u001b[32m    879\u001b[39m     )\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:1091\u001b[39m, in \u001b[36m_hf_hub_download_to_local_dir\u001b[39m\u001b[34m(local_dir, repo_id, repo_type, filename, revision, endpoint, etag_timeout, headers, proxies, token, cache_dir, force_download, local_files_only)\u001b[39m\n\u001b[32m   1089\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mstr\u001b[39m(paths.file_path)\n\u001b[32m   1090\u001b[39m     \u001b[38;5;66;03m# Otherwise => raise\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m1091\u001b[39m     \u001b[43m_raise_on_head_call_error\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhead_call_error\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mforce_download\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlocal_files_only\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1093\u001b[39m \u001b[38;5;66;03m# From now on, etag, commit_hash, url and size are not None.\u001b[39;00m\n\u001b[32m   1094\u001b[39m \u001b[38;5;28;01massert\u001b[39;00m etag \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m, \u001b[33m\"\u001b[39m\u001b[33metag must have been retrieved from server\u001b[39m\u001b[33m\"\u001b[39m\n",
            "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/anaconda3/envs/FifthyOne/lib/python3.11/site-packages/huggingface_hub/file_download.py:1489\u001b[39m, in \u001b[36m_raise_on_head_call_error\u001b[39m\u001b[34m(head_call_error, force_download, local_files_only)\u001b[39m\n\u001b[32m   1486\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m head_call_error\n\u001b[32m   1487\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   1488\u001b[39m     \u001b[38;5;66;03m# Otherwise: most likely a connection issue or Hub downtime => let's warn the user\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m1489\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m LocalEntryNotFoundError(\n\u001b[32m   1490\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mAn error happened while trying to locate the file on the Hub and we cannot find the requested files\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m   1491\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33m in the local cache. Please check your connection and try again or make sure your Internet connection\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m   1492\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33m is on.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m   1493\u001b[39m     ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mhead_call_error\u001b[39;00m\n",
            "\u001b[31mLocalEntryNotFoundError\u001b[39m: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on."
          ]
        }
      ],
      "source": [
        "import fiftyone as fo\n",
        "from fiftyone.utils.huggingface import load_from_hub\n",
        "\n",
        "# Load the dataset\n",
        "# Note: other available arguments include 'max_samples', etc\n",
        "dataset = load_from_hub(\"Chirag-R/foods\", overwrite=True)\n",
        "\n",
        "# Launch the App\n",
        "session = fo.launch_app(dataset)"
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "gpuType": "T4",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "FifthyOne",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.11"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "0c14d14957214bc28e5f3e8d5fd8e4c4": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "2ac51d4ab9d242c291ba3e34e3abf314": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "40203900a8484afdac4396a193f38c2c": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_f05c7fdf6b6a4c82a9a6ae1e6aeb9484",
            "placeholder": "​",
            "style": "IPY_MODEL_e448cd9d8838453685d0875cc6eecbb4",
            "value": " 75.0/75.0 [00:00&lt;00:00, 4.72kB/s]"
          }
        },
        "8f885de108e64e75a79430e665310679": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "ProgressStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": null,
            "description_width": ""
          }
        },
        "9938e19d3adb4d4abba24ea4f6da4381": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_f8c7eb7c18b243d793857727005bcb71",
            "placeholder": "​",
            "style": "IPY_MODEL_2ac51d4ab9d242c291ba3e34e3abf314",
            "value": "fiftyone.yml: 100%"
          }
        },
        "a23bf9ad6c044b69b95e3b9283864154": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "FloatProgressModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_0c14d14957214bc28e5f3e8d5fd8e4c4",
            "max": 75,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_8f885de108e64e75a79430e665310679",
            "value": 75
          }
        },
        "d3c02dc18d1f4119a257ba785074de8c": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "e448cd9d8838453685d0875cc6eecbb4": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "f05c7fdf6b6a4c82a9a6ae1e6aeb9484": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "f88624288f7040a0943468d69a4fcd8c": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HBoxModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_9938e19d3adb4d4abba24ea4f6da4381",
              "IPY_MODEL_a23bf9ad6c044b69b95e3b9283864154",
              "IPY_MODEL_40203900a8484afdac4396a193f38c2c"
            ],
            "layout": "IPY_MODEL_d3c02dc18d1f4119a257ba785074de8c"
          }
        },
        "f8c7eb7c18b243d793857727005bcb71": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        }
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
